### ISSUE TITLE
Module 'requests.packages' has no 'urllib3' member

### ISSUE THREAD

**Issue by leonardoporpora** [eoprede/fortigate_api#2]
By opening the pythons scripts on visual studio I saw this error: (Module 'requests.packages' has no 'urllib3' member)

**Comment by eoprede** [comment]
This is most likely due to how or whether you have installed requests library. Install/reinstall or upgrade it, maybe do something like pip install requests urllib3 pyOpenSSL

**Comment by leonardoporpora** [comment]
still have the same problem even after pip install requests urllib3 pyOpenSSL
@eoprede can we please have a chat as soon as possible in hangouts? i need your help.
Let me know,
Leonardo

**Comment by eoprede** [comment]
User decided to use something else to achieve their goals, as such this issue is no longer relevant. 
If this comes up in search - this is not a module issue, rather a requests library issue. It needs to be installed properly to function. Usually issues come when some parts of it are installed via pip and others via package managers like yum.
